[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -I src
    -DARDUINOJSON_ENABLE_COMMENTS=1

lib_deps =
    bblanchon/ArduinoJson@^7

board_build.partitions = huge_app.csv
